
        CREATE TABLE council(
        id_council CHAR(4) NOT NULL UNIQUE PRIMARY KEY,
        fk_district CHAR(2) NOT NULL REFERENCES district,
        name VARCHAR(255) NOT NULL
        );
        
INSERT INTO council(id_council, fk_district, name) VALUES('0106', '01', 'Castelo de Paiva');
INSERT INTO council(id_council, fk_district, name) VALUES('0107', '01', 'Espinho');
INSERT INTO council(id_council, fk_district, name) VALUES('0108', '01', 'Estarreja');
INSERT INTO council(id_council, fk_district, name) VALUES('0109', '01', 'Santa Maria da Feira');
INSERT INTO council(id_council, fk_district, name) VALUES('0110', '01', 'Ílhavo');
INSERT INTO council(id_council, fk_district, name) VALUES('0111', '01', 'Mealhada');
INSERT INTO council(id_council, fk_district, name) VALUES('0112', '01', 'Murtosa');
INSERT INTO council(id_council, fk_district, name) VALUES('0113', '01', 'Oliveira de Azeméis');
INSERT INTO council(id_council, fk_district, name) VALUES('0114', '01', 'Oliveira do Bairro');
INSERT INTO council(id_council, fk_district, name) VALUES('0115', '01', 'Ovar');
INSERT INTO council(id_council, fk_district, name) VALUES('0116', '01', 'São João da Madeira');
INSERT INTO council(id_council, fk_district, name) VALUES('0117', '01', 'Sever do Vouga');
INSERT INTO council(id_council, fk_district, name) VALUES('0118', '01', 'Vagos');
INSERT INTO council(id_council, fk_district, name) VALUES('0119', '01', 'Vale de Cambra');
INSERT INTO council(id_council, fk_district, name) VALUES('0101', '01', 'Águeda');
INSERT INTO council(id_council, fk_district, name) VALUES('0102', '01', 'Albergaria-a-Velha');
INSERT INTO council(id_council, fk_district, name) VALUES('0103', '01', 'Anadia');
INSERT INTO council(id_council, fk_district, name) VALUES('0104', '01', 'Arouca');
INSERT INTO council(id_council, fk_district, name) VALUES('0105', '01', 'Aveiro');
INSERT INTO council(id_council, fk_district, name) VALUES('0206', '02', 'Castro Verde');
INSERT INTO council(id_council, fk_district, name) VALUES('0207', '02', 'Cuba');
INSERT INTO council(id_council, fk_district, name) VALUES('0208', '02', 'Ferreira do Alentejo');
INSERT INTO council(id_council, fk_district, name) VALUES('0209', '02', 'Mértola');
INSERT INTO council(id_council, fk_district, name) VALUES('0210', '02', 'Moura');
INSERT INTO council(id_council, fk_district, name) VALUES('0211', '02', 'Odemira');
INSERT INTO council(id_council, fk_district, name) VALUES('0212', '02', 'Ourique');
INSERT INTO council(id_council, fk_district, name) VALUES('0213', '02', 'Serpa');
INSERT INTO council(id_council, fk_district, name) VALUES('0214', '02', 'Vidigueira');
INSERT INTO council(id_council, fk_district, name) VALUES('0201', '02', 'Aljustrel');
INSERT INTO council(id_council, fk_district, name) VALUES('0202', '02', 'Almodôvar');
INSERT INTO council(id_council, fk_district, name) VALUES('0203', '02', 'Alvito');
INSERT INTO council(id_council, fk_district, name) VALUES('0204', '02', 'Barrancos');
INSERT INTO council(id_council, fk_district, name) VALUES('0205', '02', 'Beja');
INSERT INTO council(id_council, fk_district, name) VALUES('0306', '03', 'Esposende');
INSERT INTO council(id_council, fk_district, name) VALUES('0307', '03', 'Fafe');
INSERT INTO council(id_council, fk_district, name) VALUES('0308', '03', 'Guimarães');
INSERT INTO council(id_council, fk_district, name) VALUES('0309', '03', 'Póvoa de Lanhoso');
INSERT INTO council(id_council, fk_district, name) VALUES('0310', '03', 'Terras de Bouro');
INSERT INTO council(id_council, fk_district, name) VALUES('0311', '03', 'Vieira do Minho');
INSERT INTO council(id_council, fk_district, name) VALUES('0312', '03', 'Vila Nova de Famalicão');
INSERT INTO council(id_council, fk_district, name) VALUES('0313', '03', 'Vila Verde');
INSERT INTO council(id_council, fk_district, name) VALUES('0314', '03', 'Vizela');
INSERT INTO council(id_council, fk_district, name) VALUES('0301', '03', 'Amares');
INSERT INTO council(id_council, fk_district, name) VALUES('0302', '03', 'Barcelos');
INSERT INTO council(id_council, fk_district, name) VALUES('0303', '03', 'Braga');
INSERT INTO council(id_council, fk_district, name) VALUES('0304', '03', 'Cabeceiras de Basto');
INSERT INTO council(id_council, fk_district, name) VALUES('0305', '03', 'Celorico de Basto');
INSERT INTO council(id_council, fk_district, name) VALUES('0406', '04', 'Miranda do Douro');
INSERT INTO council(id_council, fk_district, name) VALUES('0407', '04', 'Mirandela');
INSERT INTO council(id_council, fk_district, name) VALUES('0408', '04', 'Mogadouro');
INSERT INTO council(id_council, fk_district, name) VALUES('0409', '04', 'Torre de Moncorvo');
INSERT INTO council(id_council, fk_district, name) VALUES('0410', '04', 'Vila Flor');
INSERT INTO council(id_council, fk_district, name) VALUES('0411', '04', 'Vimioso');
INSERT INTO council(id_council, fk_district, name) VALUES('0412', '04', 'Vinhais');
INSERT INTO council(id_council, fk_district, name) VALUES('0401', '04', 'Alfândega da Fé');
INSERT INTO council(id_council, fk_district, name) VALUES('0402', '04', 'Bragança');
INSERT INTO council(id_council, fk_district, name) VALUES('0403', '04', 'Carrazeda de Ansiães');
INSERT INTO council(id_council, fk_district, name) VALUES('0404', '04', 'Freixo de Espada à Cinta');
INSERT INTO council(id_council, fk_district, name) VALUES('0405', '04', 'Macedo de Cavaleiros');
INSERT INTO council(id_council, fk_district, name) VALUES('0506', '05', 'Oleiros');
INSERT INTO council(id_council, fk_district, name) VALUES('0507', '05', 'Penamacor');
INSERT INTO council(id_council, fk_district, name) VALUES('0508', '05', 'Proença-a-Nova');
INSERT INTO council(id_council, fk_district, name) VALUES('0509', '05', 'Sertã');
INSERT INTO council(id_council, fk_district, name) VALUES('0510', '05', 'Vila de Rei');
INSERT INTO council(id_council, fk_district, name) VALUES('0511', '05', 'Vila Velha de Ródão');
INSERT INTO council(id_council, fk_district, name) VALUES('0501', '05', 'Belmonte');
INSERT INTO council(id_council, fk_district, name) VALUES('0502', '05', 'Castelo Branco');
INSERT INTO council(id_council, fk_district, name) VALUES('0503', '05', 'Covilhã');
INSERT INTO council(id_council, fk_district, name) VALUES('0504', '05', 'Fundão');
INSERT INTO council(id_council, fk_district, name) VALUES('0505', '05', 'Idanha-a-Nova');
INSERT INTO council(id_council, fk_district, name) VALUES('0606', '06', 'Góis');
INSERT INTO council(id_council, fk_district, name) VALUES('0607', '06', 'Lousã');
INSERT INTO council(id_council, fk_district, name) VALUES('0608', '06', 'Mira');
INSERT INTO council(id_council, fk_district, name) VALUES('0609', '06', 'Miranda do Corvo');
INSERT INTO council(id_council, fk_district, name) VALUES('0610', '06', 'Montemor-o-Velho');
INSERT INTO council(id_council, fk_district, name) VALUES('0611', '06', 'Oliveira do Hospital');
INSERT INTO council(id_council, fk_district, name) VALUES('0612', '06', 'Pampilhosa da Serra');
INSERT INTO council(id_council, fk_district, name) VALUES('0613', '06', 'Penacova');
INSERT INTO council(id_council, fk_district, name) VALUES('0614', '06', 'Penela');
INSERT INTO council(id_council, fk_district, name) VALUES('0615', '06', 'Soure');
INSERT INTO council(id_council, fk_district, name) VALUES('0616', '06', 'Tábua');
INSERT INTO council(id_council, fk_district, name) VALUES('0617', '06', 'Vila Nova de Poiares');
INSERT INTO council(id_council, fk_district, name) VALUES('0601', '06', 'Arganil');
INSERT INTO council(id_council, fk_district, name) VALUES('0602', '06', 'Cantanhede');
INSERT INTO council(id_council, fk_district, name) VALUES('0603', '06', 'Coimbra');
INSERT INTO council(id_council, fk_district, name) VALUES('0604', '06', 'Condeixa-a-Nova');
INSERT INTO council(id_council, fk_district, name) VALUES('0605', '06', 'Figueira da Foz');
INSERT INTO council(id_council, fk_district, name) VALUES('0706', '07', 'Montemor-o-Novo');
INSERT INTO council(id_council, fk_district, name) VALUES('0707', '07', 'Mora');
INSERT INTO council(id_council, fk_district, name) VALUES('0708', '07', 'Mourão');
INSERT INTO council(id_council, fk_district, name) VALUES('0709', '07', 'Portel');
INSERT INTO council(id_council, fk_district, name) VALUES('0710', '07', 'Redondo');
INSERT INTO council(id_council, fk_district, name) VALUES('0711', '07', 'Reguengos de Monsaraz');
INSERT INTO council(id_council, fk_district, name) VALUES('0712', '07', 'Vendas Novas');
INSERT INTO council(id_council, fk_district, name) VALUES('0713', '07', 'Viana do Alentejo');
INSERT INTO council(id_council, fk_district, name) VALUES('0714', '07', 'Vila Viçosa');
INSERT INTO council(id_council, fk_district, name) VALUES('0701', '07', 'Alandroal');
INSERT INTO council(id_council, fk_district, name) VALUES('0702', '07', 'Arraiolos');
INSERT INTO council(id_council, fk_district, name) VALUES('0703', '07', 'Borba');
INSERT INTO council(id_council, fk_district, name) VALUES('0704', '07', 'Estremoz');
INSERT INTO council(id_council, fk_district, name) VALUES('0705', '07', 'Évora');
INSERT INTO council(id_council, fk_district, name) VALUES('0806', '08', 'Lagoa (Algarve)');
INSERT INTO council(id_council, fk_district, name) VALUES('0807', '08', 'Lagos');
INSERT INTO council(id_council, fk_district, name) VALUES('0808', '08', 'Loulé');
INSERT INTO council(id_council, fk_district, name) VALUES('0809', '08', 'Monchique');
INSERT INTO council(id_council, fk_district, name) VALUES('0810', '08', 'Olhão');
INSERT INTO council(id_council, fk_district, name) VALUES('0811', '08', 'Portimão');
INSERT INTO council(id_council, fk_district, name) VALUES('0812', '08', 'São Brás de Alportel');
INSERT INTO council(id_council, fk_district, name) VALUES('0813', '08', 'Silves');
INSERT INTO council(id_council, fk_district, name) VALUES('0814', '08', 'Tavira');
INSERT INTO council(id_council, fk_district, name) VALUES('0815', '08', 'Vila do Bispo');
INSERT INTO council(id_council, fk_district, name) VALUES('0816', '08', 'Vila Real de Santo António');
INSERT INTO council(id_council, fk_district, name) VALUES('0801', '08', 'Albufeira');
INSERT INTO council(id_council, fk_district, name) VALUES('0802', '08', 'Alcoutim');
INSERT INTO council(id_council, fk_district, name) VALUES('0803', '08', 'Aljezur');
INSERT INTO council(id_council, fk_district, name) VALUES('0804', '08', 'Castro Marim');
INSERT INTO council(id_council, fk_district, name) VALUES('0805', '08', 'Faro');
INSERT INTO council(id_council, fk_district, name) VALUES('0906', '09', 'Gouveia');
INSERT INTO council(id_council, fk_district, name) VALUES('0907', '09', 'Guarda');
INSERT INTO council(id_council, fk_district, name) VALUES('0908', '09', 'Manteigas');
INSERT INTO council(id_council, fk_district, name) VALUES('0909', '09', 'Meda');
INSERT INTO council(id_council, fk_district, name) VALUES('0910', '09', 'Pinhel');
INSERT INTO council(id_council, fk_district, name) VALUES('0911', '09', 'Sabugal');
INSERT INTO council(id_council, fk_district, name) VALUES('0912', '09', 'Seia');
INSERT INTO council(id_council, fk_district, name) VALUES('0913', '09', 'Trancoso');
INSERT INTO council(id_council, fk_district, name) VALUES('0914', '09', 'Vila Nova de Foz Côa');
INSERT INTO council(id_council, fk_district, name) VALUES('0901', '09', 'Aguiar da Beira');
INSERT INTO council(id_council, fk_district, name) VALUES('0902', '09', 'Almeida');
INSERT INTO council(id_council, fk_district, name) VALUES('0903', '09', 'Celorico da Beira');
INSERT INTO council(id_council, fk_district, name) VALUES('0904', '09', 'Figueira de Castelo Rodrigo');
INSERT INTO council(id_council, fk_district, name) VALUES('0905', '09', 'Fornos de Algodres');
INSERT INTO council(id_council, fk_district, name) VALUES('1006', '10', 'Caldas da Rainha');
INSERT INTO council(id_council, fk_district, name) VALUES('1007', '10', 'Castanheira de Pêra');
INSERT INTO council(id_council, fk_district, name) VALUES('1008', '10', 'Figueiró dos Vinhos');
INSERT INTO council(id_council, fk_district, name) VALUES('1009', '10', 'Leiria');
INSERT INTO council(id_council, fk_district, name) VALUES('1010', '10', 'Marinha Grande');
INSERT INTO council(id_council, fk_district, name) VALUES('1011', '10', 'Nazaré');
INSERT INTO council(id_council, fk_district, name) VALUES('1012', '10', 'Óbidos');
INSERT INTO council(id_council, fk_district, name) VALUES('1013', '10', 'Pedrógão Grande');
INSERT INTO council(id_council, fk_district, name) VALUES('1014', '10', 'Peniche');
INSERT INTO council(id_council, fk_district, name) VALUES('1015', '10', 'Pombal');
INSERT INTO council(id_council, fk_district, name) VALUES('1016', '10', 'Porto de Mós');
INSERT INTO council(id_council, fk_district, name) VALUES('1001', '10', 'Alcobaça');
INSERT INTO council(id_council, fk_district, name) VALUES('1002', '10', 'Alvaiázere');
INSERT INTO council(id_council, fk_district, name) VALUES('1003', '10', 'Ansião');
INSERT INTO council(id_council, fk_district, name) VALUES('1004', '10', 'Batalha');
INSERT INTO council(id_council, fk_district, name) VALUES('1005', '10', 'Bombarral');
INSERT INTO council(id_council, fk_district, name) VALUES('1106', '11', 'Lisboa');
INSERT INTO council(id_council, fk_district, name) VALUES('1107', '11', 'Loures');
INSERT INTO council(id_council, fk_district, name) VALUES('1108', '11', 'Lourinhã');
INSERT INTO council(id_council, fk_district, name) VALUES('1109', '11', 'Mafra');
INSERT INTO council(id_council, fk_district, name) VALUES('1110', '11', 'Oeiras');
INSERT INTO council(id_council, fk_district, name) VALUES('1111', '11', 'Sintra');
INSERT INTO council(id_council, fk_district, name) VALUES('1112', '11', 'Sobral de Monte Agraço');
INSERT INTO council(id_council, fk_district, name) VALUES('1113', '11', 'Torres Vedras');
INSERT INTO council(id_council, fk_district, name) VALUES('1114', '11', 'Vila Franca de Xira');
INSERT INTO council(id_council, fk_district, name) VALUES('1115', '11', 'Amadora');
INSERT INTO council(id_council, fk_district, name) VALUES('1116', '11', 'Odivelas');
INSERT INTO council(id_council, fk_district, name) VALUES('1101', '11', 'Alenquer');
INSERT INTO council(id_council, fk_district, name) VALUES('1102', '11', 'Arruda dos Vinhos');
INSERT INTO council(id_council, fk_district, name) VALUES('1103', '11', 'Azambuja');
INSERT INTO council(id_council, fk_district, name) VALUES('1104', '11', 'Cadaval');
INSERT INTO council(id_council, fk_district, name) VALUES('1105', '11', 'Cascais');
INSERT INTO council(id_council, fk_district, name) VALUES('1206', '12', 'Crato');
INSERT INTO council(id_council, fk_district, name) VALUES('1207', '12', 'Elvas');
INSERT INTO council(id_council, fk_district, name) VALUES('1208', '12', 'Fronteira');
INSERT INTO council(id_council, fk_district, name) VALUES('1209', '12', 'Gavião');
INSERT INTO council(id_council, fk_district, name) VALUES('1210', '12', 'Marvão');
INSERT INTO council(id_council, fk_district, name) VALUES('1211', '12', 'Monforte');
INSERT INTO council(id_council, fk_district, name) VALUES('1212', '12', 'Nisa');
INSERT INTO council(id_council, fk_district, name) VALUES('1213', '12', 'Ponte de Sor');
INSERT INTO council(id_council, fk_district, name) VALUES('1214', '12', 'Portalegre');
INSERT INTO council(id_council, fk_district, name) VALUES('1215', '12', 'Sousel');
INSERT INTO council(id_council, fk_district, name) VALUES('1201', '12', 'Alter do Chão');
INSERT INTO council(id_council, fk_district, name) VALUES('1202', '12', 'Arronches');
INSERT INTO council(id_council, fk_district, name) VALUES('1203', '12', 'Avis');
INSERT INTO council(id_council, fk_district, name) VALUES('1204', '12', 'Campo Maior');
INSERT INTO council(id_council, fk_district, name) VALUES('1205', '12', 'Castelo de Vide');
INSERT INTO council(id_council, fk_district, name) VALUES('1306', '13', 'Maia');
INSERT INTO council(id_council, fk_district, name) VALUES('1307', '13', 'Marco de Canaveses');
INSERT INTO council(id_council, fk_district, name) VALUES('1308', '13', 'Matosinhos');
INSERT INTO council(id_council, fk_district, name) VALUES('1309', '13', 'Paços de Ferreira');
INSERT INTO council(id_council, fk_district, name) VALUES('1310', '13', 'Paredes');
INSERT INTO council(id_council, fk_district, name) VALUES('1311', '13', 'Penafiel');
INSERT INTO council(id_council, fk_district, name) VALUES('1312', '13', 'Porto');
INSERT INTO council(id_council, fk_district, name) VALUES('1313', '13', 'Póvoa de Varzim');
INSERT INTO council(id_council, fk_district, name) VALUES('1314', '13', 'Santo Tirso');
INSERT INTO council(id_council, fk_district, name) VALUES('1315', '13', 'Valongo');
INSERT INTO council(id_council, fk_district, name) VALUES('1316', '13', 'Vila do Conde');
INSERT INTO council(id_council, fk_district, name) VALUES('1317', '13', 'Vila Nova de Gaia');
INSERT INTO council(id_council, fk_district, name) VALUES('1318', '13', 'Trofa');
INSERT INTO council(id_council, fk_district, name) VALUES('1301', '13', 'Amarante');
INSERT INTO council(id_council, fk_district, name) VALUES('1302', '13', 'Baião');
INSERT INTO council(id_council, fk_district, name) VALUES('1303', '13', 'Felgueiras');
INSERT INTO council(id_council, fk_district, name) VALUES('1304', '13', 'Gondomar');
INSERT INTO council(id_council, fk_district, name) VALUES('1305', '13', 'Lousada');
INSERT INTO council(id_council, fk_district, name) VALUES('1406', '14', 'Cartaxo');
INSERT INTO council(id_council, fk_district, name) VALUES('1407', '14', 'Chamusca');
INSERT INTO council(id_council, fk_district, name) VALUES('1408', '14', 'Constância');
INSERT INTO council(id_council, fk_district, name) VALUES('1409', '14', 'Coruche');
INSERT INTO council(id_council, fk_district, name) VALUES('1410', '14', 'Entroncamento');
INSERT INTO council(id_council, fk_district, name) VALUES('1411', '14', 'Ferreira do Zêzere');
INSERT INTO council(id_council, fk_district, name) VALUES('1412', '14', 'Golegã');
INSERT INTO council(id_council, fk_district, name) VALUES('1413', '14', 'Mação');
INSERT INTO council(id_council, fk_district, name) VALUES('1414', '14', 'Rio Maior');
INSERT INTO council(id_council, fk_district, name) VALUES('1415', '14', 'Salvaterra de Magos');
INSERT INTO council(id_council, fk_district, name) VALUES('1416', '14', 'Santarém');
INSERT INTO council(id_council, fk_district, name) VALUES('1417', '14', 'Sardoal');
INSERT INTO council(id_council, fk_district, name) VALUES('1418', '14', 'Tomar');
INSERT INTO council(id_council, fk_district, name) VALUES('1419', '14', 'Torres Novas');
INSERT INTO council(id_council, fk_district, name) VALUES('1420', '14', 'Vila Nova da Barquinha');
INSERT INTO council(id_council, fk_district, name) VALUES('1421', '14', 'Ourém');
INSERT INTO council(id_council, fk_district, name) VALUES('1401', '14', 'Abrantes');
INSERT INTO council(id_council, fk_district, name) VALUES('1402', '14', 'Alcanena');
INSERT INTO council(id_council, fk_district, name) VALUES('1403', '14', 'Almeirim');
INSERT INTO council(id_council, fk_district, name) VALUES('1404', '14', 'Alpiarça');
INSERT INTO council(id_council, fk_district, name) VALUES('1405', '14', 'Benavente');
INSERT INTO council(id_council, fk_district, name) VALUES('1506', '15', 'Moita');
INSERT INTO council(id_council, fk_district, name) VALUES('1507', '15', 'Montijo');
INSERT INTO council(id_council, fk_district, name) VALUES('1508', '15', 'Palmela');
INSERT INTO council(id_council, fk_district, name) VALUES('1509', '15', 'Santiago do Cacém');
INSERT INTO council(id_council, fk_district, name) VALUES('1510', '15', 'Seixal');
INSERT INTO council(id_council, fk_district, name) VALUES('1511', '15', 'Sesimbra');
INSERT INTO council(id_council, fk_district, name) VALUES('1512', '15', 'Setúbal');
INSERT INTO council(id_council, fk_district, name) VALUES('1513', '15', 'Sines');
INSERT INTO council(id_council, fk_district, name) VALUES('1501', '15', 'Alcácer do Sal');
INSERT INTO council(id_council, fk_district, name) VALUES('1502', '15', 'Alcochete');
INSERT INTO council(id_council, fk_district, name) VALUES('1503', '15', 'Almada');
INSERT INTO council(id_council, fk_district, name) VALUES('1504', '15', 'Barreiro');
INSERT INTO council(id_council, fk_district, name) VALUES('1505', '15', 'Grândola');
INSERT INTO council(id_council, fk_district, name) VALUES('1606', '16', 'Ponte da Barca');
INSERT INTO council(id_council, fk_district, name) VALUES('1607', '16', 'Ponte de Lima');
INSERT INTO council(id_council, fk_district, name) VALUES('1608', '16', 'Valença');
INSERT INTO council(id_council, fk_district, name) VALUES('1609', '16', 'Viana do Castelo');
INSERT INTO council(id_council, fk_district, name) VALUES('1610', '16', 'Vila Nova de Cerveira');
INSERT INTO council(id_council, fk_district, name) VALUES('1601', '16', 'Arcos de Valdevez');
INSERT INTO council(id_council, fk_district, name) VALUES('1602', '16', 'Caminha');
INSERT INTO council(id_council, fk_district, name) VALUES('1603', '16', 'Melgaço');
INSERT INTO council(id_council, fk_district, name) VALUES('1604', '16', 'Monção');
INSERT INTO council(id_council, fk_district, name) VALUES('1605', '16', 'Paredes de Coura');
INSERT INTO council(id_council, fk_district, name) VALUES('1705', '17', 'Mondim de Basto');
INSERT INTO council(id_council, fk_district, name) VALUES('1706', '17', 'Montalegre');
INSERT INTO council(id_council, fk_district, name) VALUES('1707', '17', 'Murça');
INSERT INTO council(id_council, fk_district, name) VALUES('1708', '17', 'Peso da Régua');
INSERT INTO council(id_council, fk_district, name) VALUES('1709', '17', 'Ribeira de Pena');
INSERT INTO council(id_council, fk_district, name) VALUES('1710', '17', 'Sabrosa');
INSERT INTO council(id_council, fk_district, name) VALUES('1711', '17', 'Santa Marta de Penaguião');
INSERT INTO council(id_council, fk_district, name) VALUES('1712', '17', 'Valpaços');
INSERT INTO council(id_council, fk_district, name) VALUES('1713', '17', 'Vila Pouca de Aguiar');
INSERT INTO council(id_council, fk_district, name) VALUES('1714', '17', 'Vila Real');
INSERT INTO council(id_council, fk_district, name) VALUES('1701', '17', 'Alijó');
INSERT INTO council(id_council, fk_district, name) VALUES('1702', '17', 'Boticas');
INSERT INTO council(id_council, fk_district, name) VALUES('1703', '17', 'Chaves');
INSERT INTO council(id_council, fk_district, name) VALUES('1704', '17', 'Mesão Frio');
INSERT INTO council(id_council, fk_district, name) VALUES('1805', '18', 'Lamego');
INSERT INTO council(id_council, fk_district, name) VALUES('1806', '18', 'Mangualde');
INSERT INTO council(id_council, fk_district, name) VALUES('1807', '18', 'Moimenta da Beira');
INSERT INTO council(id_council, fk_district, name) VALUES('1808', '18', 'Mortágua');
INSERT INTO council(id_council, fk_district, name) VALUES('1809', '18', 'Nelas');
INSERT INTO council(id_council, fk_district, name) VALUES('1810', '18', 'Oliveira de Frades');
INSERT INTO council(id_council, fk_district, name) VALUES('1811', '18', 'Penalva do Castelo');
INSERT INTO council(id_council, fk_district, name) VALUES('1812', '18', 'Penedono');
INSERT INTO council(id_council, fk_district, name) VALUES('1813', '18', 'Resende');
INSERT INTO council(id_council, fk_district, name) VALUES('1814', '18', 'Santa Comba Dão');
INSERT INTO council(id_council, fk_district, name) VALUES('1815', '18', 'São João da Pesqueira');
INSERT INTO council(id_council, fk_district, name) VALUES('1816', '18', 'São Pedro do Sul');
INSERT INTO council(id_council, fk_district, name) VALUES('1817', '18', 'Sátão');
INSERT INTO council(id_council, fk_district, name) VALUES('1818', '18', 'Sernancelhe');
INSERT INTO council(id_council, fk_district, name) VALUES('1819', '18', 'Tabuaço');
INSERT INTO council(id_council, fk_district, name) VALUES('1820', '18', 'Tarouca');
INSERT INTO council(id_council, fk_district, name) VALUES('1821', '18', 'Tondela');
INSERT INTO council(id_council, fk_district, name) VALUES('1822', '18', 'Vila Nova de Paiva');
INSERT INTO council(id_council, fk_district, name) VALUES('1823', '18', 'Viseu');
INSERT INTO council(id_council, fk_district, name) VALUES('1824', '18', 'Vouzela');
INSERT INTO council(id_council, fk_district, name) VALUES('1801', '18', 'Armamar');
INSERT INTO council(id_council, fk_district, name) VALUES('1802', '18', 'Carregal do Sal');
INSERT INTO council(id_council, fk_district, name) VALUES('1803', '18', 'Castro Daire');
INSERT INTO council(id_council, fk_district, name) VALUES('1804', '18', 'Cinfães');
INSERT INTO council(id_council, fk_district, name) VALUES('3105', '31', 'Ponta do Sol');
INSERT INTO council(id_council, fk_district, name) VALUES('3106', '31', 'Porto Moniz');
INSERT INTO council(id_council, fk_district, name) VALUES('3107', '31', 'Ribeira Brava');
INSERT INTO council(id_council, fk_district, name) VALUES('3108', '31', 'Santa Cruz');
INSERT INTO council(id_council, fk_district, name) VALUES('3109', '31', 'Santana');
INSERT INTO council(id_council, fk_district, name) VALUES('3110', '31', 'São Vicente');
INSERT INTO council(id_council, fk_district, name) VALUES('3101', '31', 'Calheta (Madeira)');
INSERT INTO council(id_council, fk_district, name) VALUES('3102', '31', 'Câmara de Lobos');
INSERT INTO council(id_council, fk_district, name) VALUES('3103', '31', 'Funchal');
INSERT INTO council(id_council, fk_district, name) VALUES('3104', '31', 'Machico');
INSERT INTO council(id_council, fk_district, name) VALUES('3201', '32', 'Porto Santo');
INSERT INTO council(id_council, fk_district, name) VALUES('4101', '41', 'Vila do Porto');
INSERT INTO council(id_council, fk_district, name) VALUES('4205', '42', 'Ribeira Grande');
INSERT INTO council(id_council, fk_district, name) VALUES('4206', '42', 'Vila Franca do Campo');
INSERT INTO council(id_council, fk_district, name) VALUES('4201', '42', 'Lagoa (São Miguel)');
INSERT INTO council(id_council, fk_district, name) VALUES('4202', '42', 'Nordeste');
INSERT INTO council(id_council, fk_district, name) VALUES('4203', '42', 'Ponta Delgada');
INSERT INTO council(id_council, fk_district, name) VALUES('4204', '42', 'Povoação');
INSERT INTO council(id_council, fk_district, name) VALUES('4301', '43', 'Angra do Heroísmo');
INSERT INTO council(id_council, fk_district, name) VALUES('4302', '43', 'Praia da Vitória');
INSERT INTO council(id_council, fk_district, name) VALUES('4401', '44', 'Santa Cruz da Graciosa');
INSERT INTO council(id_council, fk_district, name) VALUES('4501', '45', 'Calheta (São Jorge)');
INSERT INTO council(id_council, fk_district, name) VALUES('4502', '45', 'Velas');
INSERT INTO council(id_council, fk_district, name) VALUES('4601', '46', 'Lajes do Pico');
INSERT INTO council(id_council, fk_district, name) VALUES('4602', '46', 'Madalena');
INSERT INTO council(id_council, fk_district, name) VALUES('4603', '46', 'São Roque do Pico');
INSERT INTO council(id_council, fk_district, name) VALUES('4701', '47', 'Horta');
INSERT INTO council(id_council, fk_district, name) VALUES('4801', '48', 'Lajes das Flores');
INSERT INTO council(id_council, fk_district, name) VALUES('4802', '48', 'Santa Cruz das Flores');
INSERT INTO council(id_council, fk_district, name) VALUES('4901', '49', 'Corvo');
